// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gumkiifulzzqwnvhbics.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1bWtpaWZ1bHp6cXdudmhiaWNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNTU1NzcsImV4cCI6MjA2MzYzMTU3N30.O-XRhwxiQSD9JTjmMe9Dx_LCf_6_81Za2II016suDIE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);